// Industria — modelo de DOS niveles: familias que contienen variantes.
// Cada familia se muestra en la vista editorial; al abrirla despliega
// sus variantes en acordeón, cada una con su ficha (specs, aplicaciones).

export const familiasIndustria = [
  {
    id: "film-stretch",
    nombre: "Film Stretch",
    categoria: "Industria",
    universo: "industria",
    tagline: "Estabilidad, protección y rendimiento para cargas industriales.",
    heroEditorial: "/productos/film-stretch/hero.jpg",
    variantes: [
      {
        id: "mini-stretch-10",
        nombre: "Mini Stretch 10 cm",
        foto: "/productos/film-stretch/mini.jpg",
        aplicacion: "Sujeción manual de piezas pequeñas, perfiles y bultos.",
        beneficio: "Autoadherencia, resistencia y flexibilidad para asegurar piezas con rapidez.",
        presentacion: "Cristal o negro · 18 a 30 micrones · elongación hasta 250%.",
      },
      {
        id: "manual-50-cristal",
        nombre: "Stretch Film Manual 50 cm Cristal",
        foto: "/productos/film-stretch/cristal.jpg",
        aplicacion: "Paletizado y protección de cargas industriales.",
        beneficio: "Aporta estabilidad, sujeción uniforme y excelente visibilidad de la carga.",
        presentacion: "20 a 25 micrones · bobinas de 4,5 a 5 kg · elongación 250% a 300%.",
      },
      {
        id: "manual-50-negro",
        nombre: "Stretch Film Manual 50 cm Negro",
        foto: "/productos/film-stretch/negro.jpg",
        aplicacion: "Paletizado con mayor privacidad y seguridad visual.",
        beneficio: "Consolida la carga y ayuda a ocultar el contenido durante la operación logística.",
        presentacion: "20 a 25 micrones · bobinas de 4,5 a 5 kg · color negro opaco.",
      },
      {
        id: "liviano-50",
        nombre: "Stretch Film Liviano 50 cm",
        foto: "/productos/film-stretch/liviano.jpg",
        aplicacion: "Uso manual frecuente para bultos medianos y tareas de embalaje dinámicas.",
        beneficio: "Mayor maniobrabilidad y rendimiento para operaciones ágiles.",
        presentacion: "Bobina liviana de 3 kg · 20 a 25 micrones · formato práctico.",
      },
      {
        id: "roma-pack",
        nombre: "Film Termocontraíble Roma Pack",
        foto: "/productos/film-stretch/roma-pack.jpg",
        aplicacion: "Consolidación de productos y cargas, desde pequeños volúmenes hasta unidades agrupadas.",
        beneficio: "Contracción uniforme, excelente presentación y protección del embalaje.",
        presentacion: "Tricapa cristal · lámina, tubo cerrado o abierto · adaptable a la necesidad del usuario.",
      },
    ],
  },
  {
    id: "flejes",
    nombre: "Flejes & Accesorios",
    categoria: "Industria",
    universo: "industria",
    tagline: "Soluciones de sujeción resistentes, seguras y de alto rendimiento.",
    heroEditorial: "/productos/flejes/hero.jpg",
    variantes: [
      {
        id: "fleje-pp-automatico",
        nombre: "Fleje PP Automático",
        foto: "/productos/flejes/automatico.jpg",
        aplicacion: "Fleje de polipropileno (PP) ideal para procesos continuos y altos volúmenes de producción, principalmente en flejadoras de pallets automáticas.",
        beneficio: "Provee estabilidad y firmeza a cargas de hasta 1000 kg. Disponible en amplia gama de medidas, colores e impresión personalizada.",
        presentacion: "Blanco cristal · tubo interior 200 o 400 mm · medidas de 06×0,60 a 15,8×0,80 mm.",
      },
      {
        id: "fleje-pp-manual",
        nombre: "Fleje PP Manual",
        foto: "/productos/flejes/manual.jpg",
        aplicacion: "Fleje de polipropileno (PP) manual, económico y fácil de usar. Provee estabilidad a cargas de hasta 1000 kg. Resistente a la humedad y a los rayos UV.",
        beneficio: "Opciones de flejado: tensor H-21 + hebilla de alambre; flejadora H-42 + precintos de chapa; o tensor H-21 + sellador H-34/H-35 + precintos de chapa PP.",
        presentacion: "Negro o blanco · con o sin tubo 200 mm · medidas de 13×1,00 a 16×0,90 mm.",
      },
      {
        id: "fleje-pp-semiautomatico",
        nombre: "Fleje PP Semiautomático",
        foto: "/productos/flejes/semiautomatico.jpg",
        aplicacion: "Fleje de polipropileno (PP) para flejadoras semiautomáticas (TP-201). Ofrece estabilidad y firmeza a cargas de hasta 1000 kg. Resistente a la humedad y a los rayos UV.",
        beneficio: "Brinda máxima seguridad en el transporte. Disponible en amplia gama de medidas y colores.",
        presentacion: "Blanco o negro · tubo interior 200 mm · medidas de 06×0,60 a 15×0,70 mm.",
      },
      {
        id: "hebillas-pet-cruzadas",
        nombre: "Hebillas PET Cruzadas",
        foto: "/productos/flejes/hebillas.jpg",
        aplicacion: "Hebillas de alambre cruzadas que permiten el deslizamiento en un solo sentido, brindando un flejado de alta tensión sin deformaciones. Muy utilizadas en maderas, cerámicos, botellas de vidrio y frutas.",
        beneficio: "Acabados: Natural (flejes PP y PET, tensor H-21) · Fosfatizada (fleje PET, tensor H-23) · Galvanizada (poliéster + PP, tensor H-26).",
        presentacion: "Medidas disponibles: 13 mm · 16 mm · 19 mm.",
      },
    ],
  },
  {
    id: "proteccion",
    nombre: "Protección para Envíos",
    categoria: "Industria",
    universo: "industria",
    tagline: "Materiales diseñados para cuidar tus productos en cada etapa del transporte.",
    heroEditorial: "/productos/proteccion/hero.jpg",
    variantes: [
      {
        id: "carton-corrugado",
        nombre: "Cartón Corrugado",
        foto: "/productos/proteccion/carton-corrugado.jpg",
        aplicacion: "Solución ideal para proteger objetos frágiles durante envíos y mudanzas. Ideal para protección, transporte y almacenamiento.",
        beneficio: "Estructura multicapa de alta resistencia a la compresión y al apilado, con excelente amortiguación de impactos. Liviano, reciclable y biodegradable.",
        presentacion: "Papel corrugado entre liners kraft · gran versatilidad de formatos y gramajes.",
      },
      {
        id: "plastico-burbuja",
        nombre: "Plástico Burbuja",
        foto: "/productos/proteccion/plastico-burbuja.jpg",
        aplicacion: "Polietileno aireado con burbujas para proteger objetos frágiles: envases, electrodomésticos, vajilla, cerámica, mudanzas y logística.",
        beneficio: "Amortigua golpes y vibraciones, transparente, liviano e impermeable. No raya ni daña superficies. Reutilizable y 100% reciclable.",
        presentacion: "Rollo de 1 m de alto × 50 m de largo · presentación Simple (una capa) o Doble (dos capas, mayor amortiguación).",
      },
      {
        id: "caja-carton-estandar",
        nombre: "Caja de Cartón Estándar",
        foto: "/productos/proteccion/caja-carton.jpg",
        aplicacion: "Cierre, almacenamiento y despacho de productos para e-commerce, droguerías, farmacéuticas, industria alimenticia y operaciones logísticas en general.",
        beneficio: "Buena resistencia estructural, armado simple y excelente relación costo-rendimiento. Cartón corrugado kraft, compatible con diferentes sistemas de cierre.",
        presentacion: "Formato versátil · disponible en diferentes medidas según necesidad.",
      },
    ],
  },
  {
    id: "cintas",
    nombre: "Cintas & Adhesivos",
    categoria: "Industria",
    universo: "industria",
    tagline: "Soluciones que garantizan un cierre seguro, fijación firme y rendimiento superior.",
    heroEditorial: "/productos/cintas/hero.jpg",
    variantes: [
      {
        id: "cinta-48",
        nombre: "Cinta de Embalaje 48 mm × 90 m",
        foto: "/productos/cintas/cinta-48.jpg",
        aplicacion: "Cierre seguro de cajas y paquetes. Logística, e-commerce, mudanzas, almacenamiento y embalaje en general.",
        beneficio: "Alta resistencia al desgarro y a la tensión. Polipropileno biorientado (BOPP) con adhesivo acrílico base agua o caucho sintético.",
        presentacion: "48 mm × 90 m · cajas por 36, 48 o 72 rollos · rollos sueltos.",
      },
      {
        id: "cinta-36",
        nombre: "Cinta de Embalaje 36 mm × 90 m",
        foto: "/productos/cintas/cinta-36.jpg",
        aplicacion: "Cierre de cajas y paquetes de peso ligero a mediano. Envoltorios, logística liviana, hogar y oficina.",
        beneficio: "Excelente adhesión. Polipropileno biorientado (BOPP) con adhesivo acrílico base agua o caucho sintético. Temperatura máxima hasta 50 °C.",
        presentacion: "36 mm × 90 m · cajas por 48, 72 o 96 rollos · rollos sueltos.",
      },
    ],
  },
];
