// =====================================================================
//  CATÁLOGO DE PRODUCTOS
//  Cada producto tiene su página inmersiva. Para agregar uno nuevo,
//  copiá un bloque y poné sus fotos en /public/productos/<id>/
// =====================================================================

export const productos = [
  {
    id: "frasco-hexagonal",
    nombre: "Frasco Hexagonal 190",
    categoria: "Envases de vidrio",
    universo: "vidrio",
    tagline: "Frasco de seis caras, distintivo para conservas gourmet y velas.",
    hero: "/productos/frasco-hexagonal/hero.jpg",
    detalles: [
      { src: "/productos/frasco-hexagonal/tapa-top.jpg", titulo: "Tapa Twist-Off 63", texto: "Cierre hermético metálico, en esta versión con acabado negro." },
      { src: "/productos/frasco-hexagonal/boca.jpg", titulo: "Boca ancha", texto: "Rosca de 63 mm compatible con tapas metálicas o plásticas twist-off." },
      { src: "/productos/frasco-hexagonal/tapa-lateral.jpg", titulo: "Forma hexagonal", texto: "Seis caras planas que aportan un look premium y facilitan el etiquetado." },
    ],
    specs: [
      { label: "Capacidad útil", value: "190 ml" },
      { label: "Capacidad a rebalse", value: "193 ml" },
      { label: "Altura", value: "74,8 – 75 mm" },
      { label: "Diagonal", value: "73,2 mm" },
      { label: "Boca", value: "Twist-Off / Axial 63 mm" },
      { label: "Material", value: "Vidrio flint transparente" },
    ],
    aplicaciones: [
      "Mermeladas y conservas gourmet",
      "Salsas y dips",
      "Velas de cera de soja",
      "Souvenirs y regalería",
    ],
    usos: [
      { src: "/productos/frasco-hexagonal/vela.jpg", nombre: "Como vela de soja" },
    ],
  },
  {
    id: "botella-cerveza",
    nombre: "Botella Cerveza 330",
    categoria: "Botellas de vidrio",
    universo: "vidrio",
    tagline: "Botella ámbar con filtro UV, ideal para cervezas artesanales.",
    hero: "/productos/botella-cerveza/hero.jpg",
    detalles: [
      { src: "/productos/botella-cerveza/chapa-top.jpg", titulo: "Tapa corona 26", texto: "Cierre de chapa corona de 26 mm, el estándar para cervezas y bebidas carbonatadas." },
      { src: "/productos/botella-cerveza/boca.jpg", titulo: "Boca corona", texto: "Boca angosta reforzada, pensada para soportar la presión del carbonatado." },
      { src: "/productos/botella-cerveza/base.jpg", titulo: "Vidrio ámbar", texto: "El color ámbar filtra los rayos UV y protege el sabor de la cerveza." },
      { src: "/productos/botella-cerveza/perfil.jpg", titulo: "Formato longneck", texto: "Perfil clásico de cuello largo, cómodo de tomar y fácil de etiquetar." },
    ],
    specs: [
      { label: "Capacidad nominal", value: "330 cc" },
      { label: "Capacidad al borde", value: "345 – 349 cc" },
      { label: "Altura", value: "210 – 225 mm" },
      { label: "Diámetro máximo", value: "60 – 63 mm" },
      { label: "Boca", value: "Corona Ø 26 mm" },
      { label: "Peso aproximado", value: "180 – 235 g" },
      { label: "Color", value: "Ámbar (filtro UV)" },
      { label: "Uso", value: "Retornable o descartable (longneck)" },
    ],
    aplicaciones: [
      "Cervezas artesanales",
      "Bebidas carbonatadas",
      "Sidras y fermentados",
      "Bebidas gourmet",
    ],
    usos: [
      { src: "/productos/botella-cerveza/etiquetada.jpg", nombre: "Etiquetada" },
      { src: "/productos/botella-cerveza/escena-cocina.jpg", nombre: "Lista para servir" },
    ],
  },
  {
    id: "frasco-yogurt",
    nombre: "Frasco Yogurt 200",
    categoria: "Envases de vidrio",
    universo: "vidrio",
    tagline: "Frasco de boca ancha con tapa a presión, ideal para lácteos y postres.",
    hero: "/productos/frasco-yogurt/hero.jpg",
    detalles: [
      { src: "/productos/frasco-yogurt/tapa-top.jpg", titulo: "Tapa plástica a presión", texto: "Cierre hermético a presión, disponible en varios colores." },
      { src: "/productos/frasco-yogurt/boca.jpg", titulo: "Boca Corona 55", texto: "Boca ancha DIN 62 de 55 mm, cómoda para llenar y consumir." },
      { src: "/productos/frasco-yogurt/abierto.jpg", titulo: "Formato individual", texto: "88 mm de altura, la porción justa para yogures y postres." },
      { src: "/productos/frasco-yogurt/base.jpg", titulo: "Vidrio alimenticio", texto: "Vidrio flint transparente de tipo alimenticio, prolijo y resistente." },
    ],
    specs: [
      { label: "Capacidad útil", value: "200 cc" },
      { label: "Capacidad a rebalse", value: "210 ml" },
      { label: "Altura", value: "87,5 – 90 mm" },
      { label: "Diámetro de base", value: "65 – 69 mm" },
      { label: "Boca", value: "Corona 55 mm (DIN 62)" },
      { label: "Peso aproximado", value: "≈ 125 g" },
      { label: "Cierre", value: "Tapa plástica a presión (varios colores)" },
    ],
    aplicaciones: [
      "Yogures y postres",
      "Dulce de leche y cremas",
      "Mousses y flanes",
      "Emprendimientos lácteos",
    ],
    usos: [
      { src: "/productos/frasco-yogurt/yogur-frutos.jpg", nombre: "Con yogur y frutos secos" },
      { src: "/productos/frasco-yogurt/yogur-arandanos.jpg", nombre: "Con yogur y arándanos" },
      { src: "/productos/frasco-yogurt/yogur-tabla.jpg", nombre: "Listo para servir" },
    ],
  },
  {
    id: "botella-jugo",
    nombre: "Botella Jugo 910",
    categoria: "Botellas de vidrio",
    universo: "vidrio",
    tagline: "Botella de línea alimentaria, ideal para jugos, lácteos y bebidas.",
    hero: "/productos/botella-jugo/hero.jpg",
    detalles: [
      { src: "/productos/botella-jugo/tapa-top.jpg", titulo: "Tapa axial 38", texto: "Cierre metálico o plástico de 38 mm, hermético y de fácil apertura." },
      { src: "/productos/botella-jugo/boca.jpg", titulo: "Boca T-OFF 38", texto: "Boca angosta pensada para el vertido de bebidas y líquidos." },
      { src: "/productos/botella-jugo/base.jpg", titulo: "Base robusta", texto: "Vidrio flint de alta resistencia, estable para llenado y transporte." },
      { src: "/productos/botella-jugo/tapa-lateral.jpg", titulo: "Perfil estilizado", texto: "Forma cilíndrica clásica de botella lechera, prolija y fácil de etiquetar." },
    ],
    specs: [
      { label: "Capacidad nominal", value: "910 cc" },
      { label: "Capacidad a rebalse", value: "930 cc" },
      { label: "Altura", value: "242 – 249 mm" },
      { label: "Diámetro", value: "78 – 90 mm" },
      { label: "Boca", value: "Axial / T-OFF 38 mm" },
      { label: "Material", value: "Vidrio cristal / flint" },
      { label: "Peso unitario", value: "≈ 405 g" },
    ],
    aplicaciones: [
      "Jugos y bebidas",
      "Lácteos y bebidas vegetales",
      "Kombucha y fermentados",
      "Emprendimientos gastronómicos",
    ],
    usos: [
      { src: "/productos/botella-jugo/con-contenido.jpg", nombre: "Con bebida" },
    ],
  },
  {
    id: "frasco-morronero",
    nombre: "Frasco Morronero 200",
    categoria: "Envases de vidrio",
    universo: "vidrio",
    tagline: "Frasco cilíndrico compacto, ideal para conservas, mieles y velas.",
    hero: "/productos/frasco-morronero/hero.jpg",
    detalles: [
      { src: "/productos/frasco-morronero/tapa-top.jpg", titulo: "Tapa Twist-Off 63", texto: "Cierre hermético metálico, disponible en dorado, negro o blanco." },
      { src: "/productos/frasco-morronero/boca.jpg", titulo: "Boca ancha roscada", texto: "Rosca de 63 mm compatible con tapas metálicas o plásticas twist-off." },
      { src: "/productos/frasco-morronero/abierto.jpg", titulo: "Formato compacto", texto: "8 cm de altura, práctico para porciones individuales y souvenirs." },
      { src: "/productos/frasco-morronero/base.jpg", titulo: "Base resistente", texto: "Vidrio incoloro de alta resistencia, apto para esterilización hogareña." },
    ],
    specs: [
      { label: "Capacidad", value: "200 ml (200 cc)" },
      { label: "Altura", value: "8,0 cm" },
      { label: "Diámetro de base", value: "6,6 – 6,9 cm" },
      { label: "Boca / Rosca", value: "Twist-Off 63 mm" },
      { label: "Material", value: "Vidrio incoloro de alta resistencia" },
      { label: "Cierre", value: "Tapa metálica (dorado, negro o blanco)" },
      { label: "Rinde en velas", value: "≈ 150–180 g de cera de soja" },
    ],
    aplicaciones: [
      "Mermeladas, dulces y salsas",
      "Encurtidos y especias",
      "Miel y souvenirs",
      "Velas de cera de soja",
    ],
    usos: [
      { src: "/productos/frasco-morronero/etiquetado.jpg", nombre: "Con miel etiquetada" },
      { src: "/productos/frasco-morronero/panal.jpg", nombre: "Con panal de miel" },
    ],
  },
  {
    id: "botella-aceite",
    nombre: "Botella Aceite 500 cc",
    categoria: "Botellas de vidrio",
    universo: "vidrio",
    tagline: "Botella cuadrada de vidrio cristal, ideal para aceites y aderezos.",
    hero: "/productos/botella-aceite/hero.jpg",
    detalles: [
      { src: "/productos/botella-aceite/tapa-top.jpg", titulo: "Tapa a rosca dorada", texto: "Cierre plástico de rosca, compatible con inserto dosificador o tapón de corcho." },
      { src: "/productos/botella-aceite/boca.jpg", titulo: "Boca B-Pilfer 31,5", texto: "Boca angosta pensada para el vertido controlado de aceites y aderezos." },
      { src: "/productos/botella-aceite/acostada.jpg", titulo: "Diseño cuadrado", texto: "Forma cuadrada estable y elegante, fácil de etiquetar en sus cuatro caras." },
      { src: "/productos/botella-aceite/perfil.jpg", titulo: "Vidrio cristal", texto: "Disponible en transparente o verde, para proteger el contenido de la luz UV." },
    ],
    specs: [
      { label: "Capacidad nominal", value: "500 cc" },
      { label: "Capacidad de rebalse", value: "526 cc" },
      { label: "Altura", value: "265,9 mm" },
      { label: "Diagonal de base", value: "73,6 mm" },
      { label: "Boca", value: "B-Pilfer 31,5 mm" },
      { label: "Peso unitario", value: "≈ 370 g" },
      { label: "Color", value: "Transparente o verde (UV)" },
      { label: "Cierre compatible", value: "Rosca con dosificador o tapón de corcho" },
    ],
    aplicaciones: [
      "Aceites de oliva y saborizados",
      "Aderezos y vinagres",
      "Aceites cosméticos",
      "Emprendimientos gourmet",
    ],
    usos: [
      { src: "/productos/botella-aceite/aceite.jpg", nombre: "Con aceite y especias" },
    ],
  },
  {
    id: "frasco-amanecer",
    nombre: "Frasco Amanecer 360",
    categoria: "Envases de vidrio",
    universo: "vidrio",
    tagline: "Vidrio cristal de alta resistencia, con tapa Twist-Off 63.",
    // Imagen principal (para la grilla y el hero de la página)
    hero: "/productos/frasco-amanecer/hero.jpg",
    // Galería de detalles (macros)
    detalles: [
      { src: "/productos/frasco-amanecer/tapa.jpg", titulo: "Tapa metálica dorada", texto: "Cierre hermético Twist-Off de 63 mm, apto para pasteurización y vacío en caliente." },
      { src: "/productos/frasco-amanecer/boca.jpg", titulo: "Boca ancha", texto: "Facilita el llenado y la extracción del contenido, incluso de piezas grandes." },
      { src: "/productos/frasco-amanecer/rosca.jpg", titulo: "Rosca T.OFF 63", texto: "Rosca estándar compatible con tapas metálicas o plásticas axiales." },
      { src: "/productos/frasco-amanecer/base.jpg", titulo: "Base reforzada", texto: "Vidrio flint de alta resistencia, estable y apto para apilado." },
    ],
    // Ficha técnica
    specs: [
      { label: "Capacidad útil", value: "360 ml (360 cc)" },
      { label: "Capacidad a rebose", value: "380 ml" },
      { label: "Altura", value: "120,5 mm" },
      { label: "Diámetro de base", value: "73 mm" },
      { label: "Boca / Rosca", value: "Twist-Off 63" },
      { label: "Material", value: "Vidrio Flint (cristal transparente)" },
      { label: "Cierre compatible", value: "Tapa metálica o plástica de rosca T-63" },
    ],
    // Aplicaciones
    aplicaciones: [
      "Mermeladas, dulces y jaleas",
      "Salsas y conservas",
      "Miel y productos artesanales",
      "Cosmética y velas de soja",
    ],
    // Versiones "en uso" (con contenido real)
    usos: [
      { src: "/productos/frasco-amanecer/miel.jpg", nombre: "Con miel" },
      { src: "/productos/frasco-amanecer/aceitunas.jpg", nombre: "Con aceitunas" },
    ],
  },
  {
    id: "frasco-gigante",
    nombre: "Frasco Gigante 3000",
    categoria: "Envases de vidrio",
    universo: "vidrio",
    tagline: "Frasco de 3 litros con boca ancha 110, ideal para conservas de gran volumen.",
    hero: "/productos/frasco-gigante/hero.jpg",
    detalles: [
      { src: "/productos/frasco-gigante/tapa-top.jpg", titulo: "Tapa a rosca blanca", texto: "Cierre plástico con guarnición interna para un sellado hermético, en acabado blanco mate." },
      { src: "/productos/frasco-gigante/boca.jpg", titulo: "Boca ancha 110", texto: "Rosca / Twist-Off de 110 mm, cómoda para llenar, extraer y manipular piezas grandes." },
      { src: "/productos/frasco-gigante/base.jpg", titulo: "Base robusta", texto: "Vidrio cristal de gran espesor, estable para soportar el volumen y el peso del contenido." },
      { src: "/productos/frasco-gigante/perfil.jpg", titulo: "Formato de 3 litros", texto: "Cuerpo cilíndrico de gran capacidad, prolijo y fácil de etiquetar en toda su altura." },
    ],
    specs: [
      { label: "Capacidad", value: "3000 ml (3 litros)" },
      { label: "Capacidad a rebalse", value: "≈ 3150 ml" },
      { label: "Altura", value: "215 – 218 mm" },
      { label: "Diámetro de base", value: "152 – 159 mm" },
      { label: "Boca / Rosca", value: "Rosca / Twist-Off 110 mm (axial)" },
      { label: "Material", value: "Vidrio cristal transparente" },
      { label: "Peso aproximado", value: "≈ 1020 g" },
      { label: "Cierre compatible", value: "Tapa plástica o metálica con guarnición (no apta para pasteurización)" },
    ],
    aplicaciones: [
      "Aceitunas y encurtidos en volumen",
      "Conservas y fermentados",
      "Almacenamiento de granos y secos",
      "Uso gastronómico y mayorista",
    ],
    usos: [
      { src: "/productos/frasco-gigante/aceitunas.jpg", nombre: "Con aceitunas" },
      { src: "/productos/frasco-gigante/aceitunas-cocina.jpg", nombre: "En la cocina" },
      { src: "/productos/frasco-gigante/escena-mesa.jpg", nombre: "Listo para servir" },
    ],
  },
  {
    id: "frasco-redondo",
    nombre: "Frasco Amanecer 250",
    categoria: "Envases de vidrio",
    universo: "vidrio",
    tagline: "Frasco cilíndrico con tapa dorada Twist-Off 63, ideal para mermeladas y velas.",
    hero: "/productos/frasco-redondo/hero.jpg",
    detalles: [
      { src: "/productos/frasco-redondo/tapa-top.jpg", titulo: "Tapa Twist-Off dorada", texto: "Cierre hermético metálico de acabado dorado, apto para vacío en caliente." },
      { src: "/productos/frasco-redondo/boca.jpg", titulo: "Boca ancha 63", texto: "Rosca Twist-Off de 63 mm, compatible con tapas metálicas o plásticas axiales." },
      { src: "/productos/frasco-redondo/base.jpg", titulo: "Base resistente", texto: "Vidrio flint de calidad alimentaria, estable y apto para esterilización hogareña." },
      { src: "/productos/frasco-redondo/perfil.jpg", titulo: "Formato individual", texto: "Cuerpo cilíndrico compacto de 7–8,5 cm, la porción justa para conservas y velas." },
    ],
    specs: [
      { label: "Capacidad útil", value: "230 – 250 ml" },
      { label: "Capacidad a rebalse", value: "≈ 233 ml" },
      { label: "Altura", value: "70 – 85 mm" },
      { label: "Diámetro de base", value: "70 mm" },
      { label: "Boca / Rosca", value: "Twist-Off / Axial 63 mm" },
      { label: "Material", value: "Vidrio transparente alimentario" },
      { label: "Cierre compatible", value: "Tapa metálica (dorada, negra o blanca), plástica o corcho" },
      { label: "Rinde en velas", value: "≈ 180–200 g de cera de soja" },
    ],
    aplicaciones: [
      "Mermeladas, dulces y conservas",
      "Aderezos, dips y miel",
      "Velas de cera de soja",
      "Souvenirs, especieros y decoración",
    ],
    usos: [
      { src: "/productos/frasco-redondo/mermelada.jpg", nombre: "Con mermelada de frutos rojos" },
      { src: "/productos/frasco-redondo/desayuno.jpg", nombre: "En la mesa del desayuno" },
    ],
  },
  {
    id: "frasco-alba",
    nombre: "Frasco Alba 660",
    categoria: "Envases de vidrio",
    universo: "vidrio",
    tagline: "Frasco alto de 660 cc con boca ancha 70, ideal para conservas y mieles.",
    hero: "/productos/frasco-alba/hero.jpg",
    detalles: [
      { src: "/productos/frasco-alba/tapa-top.jpg", titulo: "Tapa Twist-Off dorada", texto: "Cierre hermético metálico de 70 mm, apto para pasteurización y vacío en caliente." },
      { src: "/productos/frasco-alba/boca.jpg", titulo: "Boca ancha 70", texto: "Rosca axial de 70 mm, cómoda para llenar y extraer, compatible con tapas metálicas." },
      { src: "/productos/frasco-alba/base.jpg", titulo: "Base resistente", texto: "Vidrio flint de alta resistencia, apto para esterilización y lavavajillas." },
      { src: "/productos/frasco-alba/perfil.jpg", titulo: "Formato alto", texto: "Cuerpo cilíndrico estilizado de 15 cm, prolijo y fácil de etiquetar." },
    ],
    specs: [
      { label: "Capacidad", value: "660 ml (660 cc)" },
      { label: "Altura", value: "150,5 – 155 mm" },
      { label: "Diámetro", value: "86,2 – 87 mm" },
      { label: "Boca / Rosca", value: "Axial 70 mm (roscada)" },
      { label: "Material", value: "Vidrio flint de alta resistencia" },
      { label: "Cierre compatible", value: "Tapa metálica Twist-Off 70 mm (blanca, negra o dorada)" },
      { label: "Propiedades", value: "Apto esterilizar y lavavajillas, no absorbe olores ni sabores" },
    ],
    aplicaciones: [
      "Dulces, salsas y conservas",
      "Miel y productos artesanales",
      "Encurtidos y fermentados",
      "Velas de cera de soja",
    ],
    usos: [
      { src: "/productos/frasco-alba/miel.jpg", nombre: "Con miel" },
      { src: "/productos/frasco-alba/escena.jpg", nombre: "En la cocina" },
    ],
  },
  {
    id: "botella-jarabe",
    nombre: "Botella Jarabe 250",
    categoria: "Botellas de vidrio",
    universo: "vidrio",
    tagline: "Botella ámbar de 250 ml con boca 28, protege del sol y admite dosificador.",
    hero: "/productos/botella-jarabe/hero.jpg",
    detalles: [
      { src: "/productos/botella-jarabe/tapa.jpg", titulo: "Tapa a rosca con precinto", texto: "Cierre plástico estriado con precinto inviolable, para un sellado seguro." },
      { src: "/productos/botella-jarabe/boca.jpg", titulo: "Boca rosca 28", texto: "Rosca PP28 / 28-410, compatible con tapas, insertos vertedores y válvulas." },
      { src: "/productos/botella-jarabe/dosificador-detalle.jpg", titulo: "Opción dosificador", texto: "Admite bomba dosificadora a presión con traba OPEN/STOP, ideal para cremas y jabones." },
      { src: "/productos/botella-jarabe/base.jpg", titulo: "Base resistente", texto: "Vidrio Tipo III de cal sodada, apto para uso farmacéutico y alimentario." },
      { src: "/productos/botella-jarabe/abierto.jpg", titulo: "Vidrio ámbar", texto: "El color ámbar bloquea la luz UV y protege productos fotosensibles." },
    ],
    specs: [
      { label: "Capacidad", value: "250 ml (250 cc)" },
      { label: "Capacidad a rebalse", value: "≈ 252 ml" },
      { label: "Altura", value: "140,5 – 145 mm" },
      { label: "Diámetro del cuerpo", value: "50 – 62 mm" },
      { label: "Boca / Rosca", value: "PP28 / 28-410 (boca 28 mm)" },
      { label: "Material", value: "Vidrio ámbar Tipo III (cal sodada)" },
      { label: "Cierres compatibles", value: "Tapa con precinto, dosificador, atomizador, vertedor" },
      { label: "Propiedades", value: "Bloquea UV, inerte, no poroso, 100% reciclable" },
    ],
    aplicaciones: [
      "Jarabes y productos farmacéuticos",
      "Aceites esenciales y cosmética",
      "Cremas y jabones líquidos (con dosificador)",
      "Productos fotosensibles",
    ],
    usos: [
      { src: "/productos/botella-jarabe/cocina.jpg", nombre: "En la cocina" },
      { src: "/productos/botella-jarabe/vainilla.jpg", nombre: "Con vainilla" },
      { src: "/productos/botella-jarabe/escena-oscura.jpg", nombre: "Listo para etiquetar" },
    ],
  },
  {
    id: "botella-petaca",
    nombre: "Botella Petaca 200",
    categoria: "Botellas de vidrio",
    universo: "vidrio",
    tagline: "Petaca plana de 200 cc con tapa metálica, ideal para licores y aceites gourmet.",
    hero: "/productos/botella-petaca/hero.jpg",
    detalles: [
      { src: "/productos/botella-petaca/tapa-top.jpg", titulo: "Tapa metálica ciega", texto: "Cierre de aluminio con acabado plateado satinado, prolijo y hermético." },
      { src: "/productos/botella-petaca/tapa-lateral.jpg", titulo: "Rosca Pilfer 28", texto: "Boca R/28 con precinto, compatible con tapas plásticas o metálicas de 28 mm." },
      { src: "/productos/botella-petaca/abierto.jpg", titulo: "Boca ancha", texto: "Rosca estándar que facilita el llenado y el vertido de líquidos." },
      { src: "/productos/botella-petaca/perfil.jpg", titulo: "Formato petaca plano", texto: "Cuerpo chato y compacto de 14,5 cm, cómodo de transportar y de gran presencia." },
    ],
    specs: [
      { label: "Capacidad", value: "200 cc (200 ml)" },
      { label: "Capacidad a rebalse", value: "≈ 205 cc" },
      { label: "Altura", value: "145 mm" },
      { label: "Ancho de base", value: "74 – 80 mm × 33 mm" },
      { label: "Boca / Rosca", value: "Pilfer 28 (R/28, boca 28 mm)" },
      { label: "Material", value: "Vidrio flint transparente" },
      { label: "Cierre compatible", value: "Tapa plástica precintada o metálica ciega 28 mm" },
    ],
    aplicaciones: [
      "Licores artesanales, whisky, gin y fernet",
      "Aceites de oliva y vinagres gourmet",
      "Lociones, perfumes y esencias",
      "Muestras comerciales y souvenirs",
    ],
    usos: [
      { src: "/productos/botella-petaca/whisky-escena.jpg", nombre: "Con licor" },
      { src: "/productos/botella-petaca/bar-escena.jpg", nombre: "En la barra" },
    ],
  },
  {
    id: "citricos",
    nombre: "Cítricos",
    categoria: "Agro",
    universo: "agro",
    tagline: "Soluciones de empaque, protección y presentación para operaciones citrícolas.",
    hero: "/productos/citricos/hero-editorial.jpg",
    heroEditorial: "/productos/citricos/hero-editorial.jpg",
    detalles: [
      { src: "/productos/citricos/hero.jpg", titulo: "Cajas para cítricos", texto: "Cajas personalizadas con gráfica propia y cajas standard para limón, listas para responder con rapidez. Representantes de Exincor." },
      { src: "/productos/citricos/sulfito.jpg", titulo: "Papel sulfito impreso", texto: "Envoltura y presentación individual del limón, personalizable, para una imagen más cuidada. Representantes de Batiflex." },
      { src: "/productos/citricos/esquineros.jpg", titulo: "Esquineros de cartón", texto: "Protección, refuerzo y estabilización de carga paletizada. Desde 1,50 m hasta 2,30 m, simples o reforzados. Representantes de Propel S.A." },
      { src: "/productos/citricos/cajones.jpg", titulo: "Cajones cosecheros", texto: "Cajones plásticos ventilados, apilables y resistentes, para cosecha, traslado, acopio y almacenamiento de fruta fresca." },
    ],
    specs: [
      { label: "Cajas", value: "Personalizadas o standard · 17–18 kg" },
      { label: "Papel sulfito", value: "Impreso y personalizable" },
      { label: "Esquineros", value: "1,50 m a 2,30 m · simples o reforzados" },
      { label: "Cajones cosecheros", value: "Plásticos, ventilados y apilables" },
      { label: "Marcas representadas", value: "Exincor, Batiflex, Propel S.A." },
    ],
    aplicaciones: [
      "Empaque y despacho de fruta fresca",
      "Paletizado y protección de carga",
      "Cosecha, traslado y acopio en finca",
      "Presentación comercial y exportación",
    ],
    usos: [
      { src: "/productos/citricos/esquineros.jpg", nombre: "Esquineros de protección" },
      { src: "/productos/citricos/cajones.jpg", nombre: "Cajones cosecheros" },
    ],
  },
  {
    id: "frutihorticolas",
    nombre: "Frutihortícolas",
    categoria: "Agro",
    universo: "agro",
    tagline: "Soluciones de empaque para palta, frutas y hortalizas.",
    hero: "/productos/frutihorticolas/hero-editorial.jpg",
    heroEditorial: "/productos/frutihorticolas/hero-editorial.jpg",
    detalles: [
      { src: "/productos/frutihorticolas/estandar.jpg", titulo: "Diseños estándar", texto: "Cajas frutihortícolas de diseño estándar, listas para responder con rapidez a las distintas necesidades operativas del productor. Empaque, almacenamiento y despacho de palta y otros productos frutihortícolas. Representantes de la fábrica Exincor." },
      { src: "/productos/frutihorticolas/personalizada.jpg", titulo: "Cajas personalizadas", texto: "Cajas premium desarrolladas por pedido, con gráfica propia del cliente y excelente presentación comercial. Fortalecen la identidad de marca y permiten diferenciarse en el punto de venta y en la exportación." },
    ],
    specs: [
      { label: "Aplicación", value: "Palta, frutas y hortalizas" },
      { label: "Presentación habitual", value: "Cajas para palta de 8 kg y 10 kg" },
      { label: "Diseños estándar", value: "Stock listo para despacho rápido" },
      { label: "Personalizadas", value: "Gráfica propia por pedido" },
      { label: "Marca representada", value: "Exincor" },
    ],
    aplicaciones: [
      "Empaque, almacenamiento y despacho de palta",
      "Líneas frutihortícolas con identidad de marca",
      "Presentación comercial en punto de venta",
      "Exportación y diferenciación premium",
    ],
    usos: [
      { src: "/productos/frutihorticolas/estandar.jpg", nombre: "Cajas estándar" },
      { src: "/productos/frutihorticolas/personalizada.jpg", nombre: "Cajas personalizadas" },
    ],
  },
  {
    id: "berries",
    nombre: "Berries",
    categoria: "Agro",
    universo: "agro",
    tagline: "Empaque y presentación para arándanos, frutillas y frutos rojos frescos.",
    hero: "/productos/berries/hero-editorial.jpg",
    heroEditorial: "/productos/berries/hero-editorial.jpg",
    detalles: [
      { src: "/productos/berries/arandanos-caja.jpg", titulo: "Cajas de arándanos", texto: "Cajas de 1,5 y 2 kg diseñadas para proteger la fruta durante operaciones comerciales y de exportación. Excelente presencia, protección y practicidad operativa para el empaque, almacenamiento y despacho de arándanos frescos." },
      { src: "/productos/berries/clamshells.jpg", titulo: "Clamshells de 125 y 170 g", texto: "Estuches transparentes de PET termoformado, con tapa y base unidas por bisagra. Ventilación para cadena de frío, cierre a presión, aptos para alimentos y reciclables. Protección, ventilación y conservación de arándanos y frutos rojos." },
      { src: "/productos/berries/frutillas.jpg", titulo: "Cajas de frutillas", texto: "Bandejas para frutas seleccionadas, con ventilación y refuerzo para fruta preenfriada. Pensadas para mantener la cadena de frío a 2 °C y proteger la fruta hasta el punto de venta." },
    ],
    specs: [
      { label: "Cajas de arándanos", value: "1,5 kg y 2 kg" },
      { label: "Clamshells", value: "125 g y 170 g · PET termoformado" },
      { label: "Cajas de frutillas", value: "Bandejas para fruta preenfriada" },
      { label: "Características clamshell", value: "Ventilados, cierre a presión y reciclables" },
      { label: "Aptitud", value: "Empaque comercial y de exportación" },
    ],
    aplicaciones: [
      "Empaque, almacenamiento y despacho de arándanos frescos",
      "Presentación y conservación en clamshells ventilados",
      "Empaque de frutillas con cadena de frío a 2 °C",
      "Operaciones comerciales y de exportación",
    ],
    usos: [
      { src: "/productos/berries/clamshells.jpg", nombre: "Clamshells de arándanos" },
      { src: "/productos/berries/frutillas.jpg", nombre: "Cajas de frutillas" },
    ],
  },
  {
    id: "tratamiento",
    nombre: "Tratamiento y Mantenimiento",
    categoria: "Agro",
    universo: "agro",
    tagline: "Ceras y componentes Wassington para el brillo, mantenimiento y funcionamiento del proceso citrícola.",
    hero: "/productos/tratamiento/hero-editorial.jpg",
    heroEditorial: "/productos/tratamiento/hero-editorial.jpg",
    detalles: [
      { src: "/productos/tratamiento/citrowax.jpg", titulo: "Citrowax M5", texto: "Cera para exportación. Disponible en tambor y contenedor. Mejora el brillo y la presentación de la fruta." },
      { src: "/productos/tratamiento/emulcol.jpg", titulo: "Emulcol MI", texto: "Cera para mercado interno. Disponible en tambor y contenedor. Protección y terminación uniforme." },
      { src: "/productos/tratamiento/panter.jpg", titulo: "Panter H", texto: "Desengrasante limpia hornos. Limpieza eficiente para hornos y máquinas en operaciones industriales." },
      { src: "/productos/tratamiento/detersol.jpg", titulo: "Detersol FW", texto: "Lavador para fruta cítrica. Remueve suciedad adherida y fumagina en post-cosecha. Alta humectación, sin acción desinfectante." },
    ],
    specs: [
      { label: "Citrowax M5", value: "Cera de exportación · tambor o contenedor" },
      { label: "Emulcol MI", value: "Cera mercado interno · tambor o contenedor" },
      { label: "Panter H", value: "Desengrasante limpia hornos · 5 L" },
      { label: "Detersol FW", value: "Lavador de fruta cítrica · 5 L" },
      { label: "Marca", value: "Wassington" },
    ],
    aplicaciones: [
      "Encerado y brillo de fruta para exportación",
      "Terminación para mercado interno",
      "Limpieza de hornos y máquinas de empaque",
      "Lavado de fruta en post-cosecha",
    ],
    usos: [
      { src: "/productos/tratamiento/panter.jpg", nombre: "Panter H · limpieza de máquinas" },
      { src: "/productos/tratamiento/detersol.jpg", nombre: "Detersol FW · lavado de fruta" },
    ],
  },
];

export const getProducto = (id) => productos.find((p) => p.id === id);
